import { v4 as uuidv4 } from "uuid";
import type { ICPKnowledgeBase, ICPCriterion } from "./types";

/**
 * Default TGA ICP Knowledge Base — Version 1.0
 * This is the seed data; all future changes go through the API.
 */
export const DEFAULT_ICP_KNOWLEDGE_BASE: ICPKnowledgeBase = {
  version: "1.0",
  name: "TGA Ideal Customer Profile",
  description:
    "B2B product and platform companies across IT, SaaS, manufacturing, semiconductor, industrial, cybersecurity, HRMS, fintech, analytics, robotics, and logistics — excluding generic service providers.",
  criteria: [
    {
      id: "target_industries",
      name: "Target Industries",
      description:
        "Product-led and platform companies in TGA's core verticals. Manufacturing, semiconductor, and industrial B2B are high-priority targets.",
      type: "industry",
      weight: 29,
      required: true,
      active: true,
      order: 0,
      isHardRule: false,
      rules: [],
      values: [
        "IT Products",
        "SaaS Companies",
        "Manufacturing",
        "Semiconductor",
        "Industrial B2B",
        "Electronics Manufacturing",
        "Hardware B2B",
        "Industrial Automation",
        "Cyber Security",
        "Cybersecurity Consultants",
        "Building & Admin Management",
        "HRMS",
        "Talent Lifecycle Management Software",
        "Training & Learning Solutions",
        "Analytics",
        "AI",
        "BI & ML",
        "Robotics & Automation",
        "Logistics & Supply Chain",
        "WMS",
        "PLM",
        "Business Development Software",
        "Sales Software",
        "Fintech",
        "Manufacturing B2B Offerings",
      ],
      positiveSignals: [
        "Manufacturing company with B2B products or components",
        "Semiconductor, chip design, or fabrication company",
        "Industrial equipment or machinery manufacturer",
        "Owns a proprietary software product or platform",
        "Product-led B2B company",
        "Vertical SaaS with a defined niche",
        "Examples: Veris, 75F, KloudLearn, Lecturio, SkaleUp, OneBill, UV Robots",
      ],
      negativeSignals: [
        "Agency or body-shop model",
        "Project-based services without own product",
        "Generic IT outsourcing",
      ],
    },
    {
      id: "priority_manufacturing_semiconductor",
      name: "Priority: Manufacturing & Semiconductor",
      description:
        "Informational only — flags high-priority verticals (manufacturing, semiconductor, industrial B2B). Does not affect ICP score.",
      type: "industry",
      weight: 0,
      required: false,
      active: true,
      order: 1,
      isHardRule: false,
      rules: [],
      values: [
        "Manufacturing",
        "Semiconductor",
        "Semiconductors",
        "Industrial B2B",
        "Electronics Manufacturing",
        "Hardware B2B",
        "Industrial Automation",
        "Precision Manufacturing",
        "Contract Manufacturing",
        "OEM B2B",
        "Chip Design",
        "Fabrication",
        "Industrial Equipment",
        "Machinery Manufacturing",
      ],
      positiveSignals: [
        "B2B manufacturing with global go-to-market",
        "Semiconductor or electronics component supplier",
        "Industrial automation or robotics manufacturer",
        "OEM selling to other businesses",
        "High-priority vertical — strong fit for TGA",
      ],
      negativeSignals: [
        "Pure consumer retail manufacturing with no B2B line",
        "Manufacturing-only job shop with no product brand",
      ],
    },
    {
      id: "employee_size",
      name: "Company Size",
      description:
        "Employee count range for ideal customers. Contributes to weighted score — outside range lowers score but does not auto-disqualify.",
      type: "employee_size",
      weight: 10,
      required: false,
      active: true,
      order: 2,
      isHardRule: false,
      minValue: 50,
      maxValue: 1000,
      rules: [
        {
          id: "emp_min",
          field: "employee_count",
          operator: "gte",
          value: 50,
          description: "Minimum 50 employees",
          isHardRule: false,
        },
        {
          id: "emp_max",
          field: "employee_count",
          operator: "lte",
          value: 1000,
          description: "Maximum 1000 employees",
          isHardRule: false,
        },
      ],
    },
    {
      id: "target_geography",
      name: "Target Geography",
      description:
        "Companies headquartered or actively operating in India, MEA (Middle East & Africa), SEA (Southeast Asia), or USA. Contributes to weighted score — outside target regions lowers score but does not auto-disqualify.",
      type: "country",
      weight: 18,
      required: false,
      active: true,
      order: 3,
      isHardRule: false,
      rules: [],
      values: ["India", "MEA", "SEA", "USA"],
      positiveSignals: [
        "Headquartered in India, USA, Middle East, Africa, or Southeast Asia",
        "Active go-to-market in target regions",
      ],
    },
    {
      id: "business_model",
      name: "Business Model",
      description: "Must be a B2B product or platform company — not a generic service provider.",
      type: "business_model",
      weight: 12,
      required: true,
      active: true,
      order: 5,
      isHardRule: false,
      rules: [],
      preferredModels: ["B2B"],
      positiveSignals: [
        "Subscription or license-based product",
        "Enterprise B2B sales motion",
        "Manufacturing with B2B offerings",
        "Semiconductor or industrial B2B sales",
      ],
      negativeSignals: [
        "Pure services agency",
        "Staff augmentation",
        "Project outsourcing",
      ],
    },
    {
      id: "excluded_lead_gen_competitors",
      name: "Excluded: B2B Lead Gen & Demand Gen",
      description:
        "TGA is a B2B lead generation company. Direct competitors offering lead generation or demand generation services are automatically rejected with score 0.",
      type: "exclusion",
      weight: 0,
      required: true,
      active: true,
      order: 6,
      isHardRule: true,
      rules: [],
      values: [
        "B2B Lead Generation",
        "Lead Generation",
        "Demand Generation",
        "Demand Gen",
        "Lead Gen Agency",
        "Lead Generation Services",
        "Demand Generation Services",
        "Outbound Lead Generation",
        "Sales Development Services",
        "Appointment Setting",
        "BDR Services",
        "SDR Services",
        "Pipeline Generation",
        "Qualified Leads Provider",
        "Sales Leads Agency",
      ],
      positiveSignals: [],
      negativeSignals: [
        "B2B lead generation",
        "demand generation",
        "demand gen",
        "lead gen agency",
        "we generate leads for",
        "qualified B2B leads",
        "appointment setting services",
        "sales development outsourcing",
        "outbound lead generation",
        "pipeline generation services",
        "delivering sales & marketing solutions",
      ],
    },
    {
      id: "excluded_solar_renewables",
      name: "Excluded: Solar & Renewables",
      description:
        "Companies whose PRIMARY business is solar energy, renewable power, wind, or clean-tech energy generation — automatically disqualify. Does NOT apply to product/automation companies that serve solar clients or mention solar in sustainability copy.",
      type: "exclusion",
      weight: 0,
      required: true,
      active: true,
      order: 7,
      isHardRule: true,
      rules: [],
      values: [
        "Solar Energy",
        "Solar Power",
        "Renewable Energy",
        "Renewables",
        "Clean Energy",
        "Wind Energy",
        "Wind Power",
        "Photovoltaic",
        "Solar Panel",
        "Solar EPC",
        "Green Energy",
        "Solar Installation",
      ],
      positiveSignals: [],
      negativeSignals: [
        "solar panel manufacturer",
        "solar panel installation",
        "solar EPC contractor",
        "renewable energy solutions provider",
        "wind farm developer",
        "clean energy provider",
        "photovoltaic modules",
      ],
    },
    {
      id: "excluded_services",
      name: "Excluded Service Providers",
      description:
        "Pure generic service agencies (web dev shops, marketing agencies, staff aug) — automatically disqualify. Companies with own IT products/platforms that also offer services are INCLUDED.",
      type: "exclusion",
      weight: 0,
      required: true,
      active: true,
      order: 8,
      isHardRule: true,
      rules: [],
      values: [
        "Web Development",
        "Web Development Services",
        "Website Development Agency",
        "Marketing Agency",
        "Marketing Services",
        "Digital Marketing Agency",
        "Generic IT Services",
        "IT Consulting Services",
        "Staff Augmentation",
        "Outsourcing Services",
        "Freelance Agency",
      ],
      positiveSignals: [],
      negativeSignals: [
        "We build websites for clients",
        "Full-service marketing agency",
        "Hire our developers",
        "Custom development services",
        "Generic digital agency",
      ],
    },
    {
      id: "company_characteristics",
      name: "Company Characteristics",
      description: "Qualitative signals — product company vs generic service provider.",
      type: "company_characteristic",
      weight: 6,
      required: false,
      active: true,
      order: 9,
      isHardRule: false,
      rules: [],
      positiveSignals: [
        "Own product or platform mentioned prominently",
        "Offers both proprietary products AND consulting/services (hybrid IT company)",
        "Case studies about product adoption, not just project delivery",
        "Pricing page or product tiers",
        "Active product development and roadmap",
        "Manufacturing company with B2B product line",
        "Semiconductor or industrial company selling B2B",
      ],
      negativeSignals: [
        "Portfolio of client websites built",
        "Services menu: web dev, SEO, social media",
        "No own product — only client work",
        "Staffing or body-shop language",
      ],
    },
  ],
  metadata: {
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    updatedBy: "System",
    changeSummary: "Initial TGA ICP v1.0 — product-led B2B companies in India, MEA, SEA, USA",
  },
};

export function createCriterion(
  partial: Partial<ICPCriterion> & Pick<ICPCriterion, "name" | "type">
): ICPCriterion {
  const maxOrder = DEFAULT_ICP_KNOWLEDGE_BASE.criteria.length;
  return {
    id: partial.id ?? uuidv4(),
    name: partial.name,
    description: partial.description ?? "",
    type: partial.type,
    weight: partial.weight ?? 10,
    required: partial.required ?? false,
    active: partial.active ?? true,
    order: partial.order ?? maxOrder,
    isHardRule: partial.isHardRule ?? false,
    rules: partial.rules ?? [],
    positiveSignals: partial.positiveSignals ?? [],
    negativeSignals: partial.negativeSignals ?? [],
    values: partial.values,
    minValue: partial.minValue,
    maxValue: partial.maxValue,
    preferredModels: partial.preferredModels,
  };
}
